<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="6" passed="5">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="86" started-at="2019-06-23T12:09:41Z" finished-at="2019-06-23T12:09:41Z">
    <groups>
      <group name="Sanity">
        <method signature="TestNgExamples.test1()[pri:3, instance:com.testng.tutorials.TestNgExamples@6cc4c815]" name="test1" class="com.testng.tutorials.TestNgExamples"/>
        <method signature="TestNgExamples.test2()[pri:1, instance:com.testng.tutorials.TestNgExamples@6cc4c815]" name="test2" class="com.testng.tutorials.TestNgExamples"/>
      </group> <!-- Sanity -->
      <group name="Regression">
        <method signature="TestNgExamples.test4()[pri:6, instance:com.testng.tutorials.TestNgExamples@6cc4c815]" name="test4" class="com.testng.tutorials.TestNgExamples"/>
      </group> <!-- Regression -->
      <group name="E2E">
        <method signature="TestNgExamples.test3()[pri:2, instance:com.testng.tutorials.TestNgExamples@6cc4c815]" name="test3" class="com.testng.tutorials.TestNgExamples"/>
      </group> <!-- E2E -->
    </groups>
    <test name="Default test" duration-ms="86" started-at="2019-06-23T12:09:41Z" finished-at="2019-06-23T12:09:41Z">
      <class name="com.testng.tutorials.TestNgExamples">
        <test-method status="PASS" signature="test2()[pri:1, instance:com.testng.tutorials.TestNgExamples@6cc4c815]" name="test2" duration-ms="19" started-at="2019-06-23T17:39:41Z" description="Performs simple test2" finished-at="2019-06-23T17:39:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method status="PASS" signature="test3()[pri:2, instance:com.testng.tutorials.TestNgExamples@6cc4c815]" name="test3" duration-ms="4" started-at="2019-06-23T17:39:41Z" description="Performs simple test3" finished-at="2019-06-23T17:39:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test3 -->
        <test-method status="PASS" signature="test1()[pri:3, instance:com.testng.tutorials.TestNgExamples@6cc4c815]" name="test1" duration-ms="2" started-at="2019-06-23T17:39:41Z" description="Performs simple test" finished-at="2019-06-23T17:39:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method status="FAIL" signature="test5()[pri:4, instance:com.testng.tutorials.TestNgExamples@6cc4c815]" name="test5" duration-ms="4" started-at="2019-06-23T17:39:41Z" description="Performs simple test5" finished-at="2019-06-23T17:39:41Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at com.testng.tutorials.TestNgExamples.test5(TestNgExamples.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test5 -->
        <test-method status="PASS" signature="test6()[pri:5, instance:com.testng.tutorials.TestNgExamples@6cc4c815]" name="test6" duration-ms="2" started-at="2019-06-23T17:39:41Z" description="Performs simple test6" finished-at="2019-06-23T17:39:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test6 -->
        <test-method status="PASS" signature="test4()[pri:6, instance:com.testng.tutorials.TestNgExamples@6cc4c815]" name="test4" duration-ms="1" started-at="2019-06-23T17:39:41Z" description="Performs simple test4" finished-at="2019-06-23T17:39:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test4 -->
      </class> <!-- com.testng.tutorials.TestNgExamples -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
